# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "react-redux"
        update-types: ["version-update:semver-major"]
      - dependency-name: "redux"
        update-types: ["version-update:semver-major"]
      - dependency-name: "redux-thunk"
        update-types: ["version-update:semver-major"]
    groups:
      # Group @typescript-eslint dependencies together
      typescript-eslint:
        patterns:
        - "@typescript-eslint/*"
